# Modular Arithmetic

The modulo operator $a$ $mod$ $n$ = $b$, where $b$ is the residue
The congruence operator is that when divided by $n$ the values $a$ and $b$ have the same remainder
$ a \equiv b (\mod n)$

A property known of $b$  exists in  $0 \leq b \leq n - 1$

Residue classes, this is the set of residues given a module $n$

In [6]:
from math import ceil
import numpy as np

def residueClassMatrix(module, limit=7):
    numberOfColumns = module
    numberOfRows = limit
    startValue = ceil(limit/2) * -module
    matrix = np.zeros((numberOfRows, numberOfColumns), dtype=int)
    for i in range(limit):
        for j in range(numberOfColumns):
            value = startValue
            matrix[i, j] = value
            startValue += 1
    return matrix

print(residueClassMatrix(7))

[[-28 -27 -26 -25 -24 -23 -22]
 [-21 -20 -19 -18 -17 -16 -15]
 [-14 -13 -12 -11 -10  -9  -8]
 [ -7  -6  -5  -4  -3  -2  -1]
 [  0   1   2   3   4   5   6]
 [  7   8   9  10  11  12  13]
 [ 14  15  16  17  18  19  20]]


This is an example of the module 7, as it can be seen the # of classes is $n-1$ from ${0, 1, 2, 3, 4 ... 6}$  and the families are each column 
```
[[-28 -27 -26 -25 -24 -23 -22]
 [-21 -20 -19 -18 -17 -16 -15]
 [-14 -13 -12 -11 -10  -9  -8]
 [ -7  -6  -5  -4  -3  -2  -1]
 [  0   1   2   3   4   5   6]
 [  7   8   9  10  11  12  13]
 [ 14  15  16  17  18  19  20]]
```

## Operations

The $\bmod$ operator maps all integers into the set $\{0,1,\dots,n-1\}$. This reduction property can be applied to addition, multiplication and exponentiation:

- $(a + b) \bmod n = \big((a \bmod n) + (b \bmod n)\big) \bmod n$
- $(a - b) \bmod n = \big((a \bmod n) - (b \bmod n)\big) \bmod n$
- $(a \times b) \bmod n = \big((a \bmod n) \times (b \bmod n)\big) \bmod n$

Exponentiation and modular reduction

A clean (congruence) formulation is:

$$a^t \equiv a^{t'}\,a^{t''}\,a^{t'''} \pmod{n}\quad\text{when}\quad t = t' + t'' + t'''.$$

Equivalently, taking representatives in $\{0,\dots,n-1\}$,

$$a^t \bmod n = \Big(\big(a^{t'} \bmod n\big)\cdot\big(a^{t''} \bmod n\big)\cdot\big(a^{t'''} \bmod n\big)\Big)\bmod n.$$

This follows from the distributive property of the modulus over multiplication:

$$(x\cdot y) \bmod n = \big( (x\bmod n)\cdot (y\bmod n) \big) \bmod n.$$

Practical decomposition (binary / repeated squaring)

Write the exponent $t$ in binary: $t = \sum_{i=0}^{k} t_i 2^i$ with $t_i\in\{0,1\}$. Then

$$a^t = \prod_{i:\,t_i=1} a^{2^i},$$

so in modular arithmetic

$$a^t \bmod n = \prod_{i:\,t_i=1} \big(a^{2^i} \bmod n\big) \bmod n.$$

Algorithmically this gives the standard "repeated squaring" method: compute $a^{2^0}, a^{2^1}, a^{2^2},\dots$ by successive squaring modulo $n$, and multiply those with corresponding $t_i=1$ reducing modulo $n$ at each step.

Example: $a=3$, $t=13 = (1101)_2 = 8+4+1$

- Compute $3^{1}\bmod n$, $3^{2}\bmod n$, $3^{4}\bmod n$, $3^{8}\bmod n$ by squaring each time and reducing mod $n$.
- Then $3^{13} \bmod n = (3^{8}\bmod n)\cdot(3^{4}\bmod n)\cdot(3^{1}\bmod n)\bmod n$.


In [7]:
def modOperation(a, b, n, operation):
    if operation == 'add':
        print(f"({a} mod {n} + {b} mod {n}) mod {n}")
        print(f"= ({a % n} + {b % n}) mod {n}")
        return (a % n + b % n) % n
    elif operation == 'sub':
        print(f"({a} mod {n} - {b} mod {n}) mod {n}")
        print(f"= ({a % n} - {b % n}) mod {n}")
        return (a % n - b % n) % n
    elif operation == 'mul':
        print(f"({a} mod {n} * {b} mod {n}) mod {n}")
        print(f"= ({a % n} * {b % n}) mod {n}")
        return (a % n * b % n) % n
    else:
        raise ValueError("Unsupported operation. Use 'add', 'sub', or 'mul'.")

# Demonstration of modular operations properties:
# Addition
a = 11
b = 15
n = 8
resultTheoretical = (a + b) % n
print(f"Theoretical Result of ({a} + {b}) mod {n} = {resultTheoretical}")
print("Using modular addition property:")
print(modOperation(a, b, n, 'add'))

# Subtraction
a = 11
b = 15
n = 8
resultTheoretical = (a - b) % n
print(f"Theoretical Result of ({a} - {b}) mod {n} = {resultTheoretical}")
print("Using modular subtraction property:")
print(modOperation(a, b, n, 'sub'))

# Multiplication
a = 11
b = 15
n = 8
resultTheoretical = (a * b) % n
print(f"Theoretical Result of ({a} * {b}) mod {n} = {resultTheoretical}")
print("Using modular multiplication property:")
print(modOperation(a, b, n, 'mul'))

# Demonstration of modular reduction

a_base = 11
a_exp = 13
n = 53
# Theoretical calculation
theoretical_result = pow(a_base, a_exp) % n
print(f"Theoretical Result of ({a_base}^{a_exp}) mod {n} = {theoretical_result}")
# Using modular reduction property
reduced_base = a_base % n
reduced_exponent = a_exp % (n - 1)  # Using Fermat's little theorem
reduced_result = pow(reduced_base, reduced_exponent) % n
print(f"Using modular reduction property: ({reduced_base}^{reduced_exponent}) mod {n} = {reduced_result}")

# Subdividing exponents
a_exp1 = 6
a_exp2 = 7
result1 = pow(a_base, a_exp1) % n
result2 = pow(a_base, a_exp2) % n
combined_result = (result1 * result2) % n
print(f"Using subdivided exponents: ({a_base}^{a_exp1} mod {n}) * ({a_base}^{a_exp2} mod {n}) mod {n} = {combined_result}")

Theoretical Result of (11 + 15) mod 8 = 2
Using modular addition property:
(11 mod 8 + 15 mod 8) mod 8
= (3 + 7) mod 8
2
Theoretical Result of (11 - 15) mod 8 = 4
Using modular subtraction property:
(11 mod 8 - 15 mod 8) mod 8
= (3 - 7) mod 8
4
Theoretical Result of (11 * 15) mod 8 = 5
Using modular multiplication property:
(11 mod 8 * 15 mod 8) mod 8
= (3 * 7) mod 8
5
Theoretical Result of (11^13) mod 53 = 52
Using modular reduction property: (11^13) mod 53 = 52
Using subdivided exponents: (11^6 mod 53) * (11^7 mod 53) mod 53 = 52


### Properties related to the congruence operator $\equiv$


- if $(a+b) \equiv (a+c) \mod n$ then $ b \equiv  c \mod n $

"This means $c$ and $b$ will have the same remainder when divided by $n$ if when added by $a + b$ and $a + c$ also have the same remainder divided by $n$"

- if $(ab) \equiv (ac) \mod n$ then $ b \equiv  c \mod n $ only if $a$ is coprime to $n$ ($GCD(a,n) = 1$)




In [8]:
def congruenceProperty(a, b, c, n, operation):
    if operation == 'add':
        left = (a + b) % n
        right = (a + c) % n
        print(f"Checking if ({a} + {b}) mod {n} == ({a} + {c}) mod {n}")
        return left == right
    elif operation == 'mul':
        left = (a * b) % n
        right = (a * c) % n
        print(f"Checking if ({a} * {b}) mod {n} == ({a} * {c}) mod {n}")
        return left == right
    else:
        raise ValueError("Unsupported operation. Use 'add' or 'mul'.")

# Example usage of congruence properties
a = 5
b = 23
c = 7
n = 8
print("Addition Property:", congruenceProperty(a, b, c, n, 'add'))
print("Multiplication Property:", congruenceProperty(a, b, c, n, 'mul'))

Checking if (5 + 23) mod 8 == (5 + 7) mod 8
Addition Property: True
Checking if (5 * 23) mod 8 == (5 * 7) mod 8
Multiplication Property: True


### Additive Inverse and Multiplicative Inverse

The additive inverse is

$a + (-a) = (-a)(+a) = 0$


The multiplicative inverse is 

$a^{-1}a = 1$

In module this means
The additive inverse is from $x$ to $y$ given a $n$
$(x+y)\mod n = 0$

The multiplicative inverse is 
$(x\times y) \mod n = 1$
An integer has a multiplicative inverse in $Z_n$ if it is coprime to $n


In [9]:
def additiveInverseMatrix(n):
    matrix = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            matrix[i, j] = (i + j) % n
    return matrix

def multiplicativeInverseMatrix(n):
    matrix = np.zeros((n, n), dtype=int)
    for i in range(n):
        for j in range(n):
            matrix[i, j] = (i * j) % n
    return matrix

def additiveInverse(n):
    matrix = np.zeros((n, 2), dtype=int)
    for i in range(n):
        matrix[i, 0] = i
        matrix[i, 1] = (-i) % n
    return matrix

def multiplicativeInverse(n):
    matrix = np.zeros((n, 2), dtype=int)
    for i in range(1, n):
        for j in range(1, n):
            if (i * j) % n == 1:
                matrix[i, 0] = i
                matrix[i, 1] = j
                break
    return matrix

def print_matrix_table(mat, n, title):
    """Print an n x n matrix with headers 0..n-1 for columns and rows."""
    print(title)
    # header
    header = '    | ' + ''.join(f'{j:4}' for j in range(n))
    sep = '----+' + '----'*n
    print(header)
    print(sep)
    for i in range(n):
        row = ''.join(f'{mat[i,j]:4}' for j in range(n))
        print(f'{i:3} |' + row)
    print()

def print_pairs_table(pairs, n, title):
    """Print pairs (x, inverse) for x in 0..n-1."""
    print(title)
    print(' x | inv')
    print('----+----')
    for i in range(n):
        print(f'{pairs[i,0]:3} | {pairs[i,1]:3}')
    print()

# Demonstration with n=8
n = 8
add_mat = additiveInverseMatrix(n)
mul_mat = multiplicativeInverseMatrix(n)
add_pairs = additiveInverse(n)
mul_pairs = multiplicativeInverse(n)

print_matrix_table(add_mat, n, 'Addition table (i + j) mod n:')
print_matrix_table(mul_mat, n, 'Multiplication table (i * j) mod n:')
print_pairs_table(add_pairs, n, 'Additive inverses (x -> -x mod n):')
print_pairs_table(mul_pairs, n, 'Multiplicative inverses (x -> x^{-1} mod n) [0 means no inverse]:')

Addition table (i + j) mod n:
    |    0   1   2   3   4   5   6   7
----+--------------------------------
  0 |   0   1   2   3   4   5   6   7
  1 |   1   2   3   4   5   6   7   0
  2 |   2   3   4   5   6   7   0   1
  3 |   3   4   5   6   7   0   1   2
  4 |   4   5   6   7   0   1   2   3
  5 |   5   6   7   0   1   2   3   4
  6 |   6   7   0   1   2   3   4   5
  7 |   7   0   1   2   3   4   5   6

Multiplication table (i * j) mod n:
    |    0   1   2   3   4   5   6   7
----+--------------------------------
  0 |   0   0   0   0   0   0   0   0
  1 |   0   1   2   3   4   5   6   7
  2 |   0   2   4   6   0   2   4   6
  3 |   0   3   6   1   4   7   2   5
  4 |   0   4   0   4   0   4   0   4
  5 |   0   5   2   7   4   1   6   3
  6 |   0   6   4   2   0   6   4   2
  7 |   0   7   6   5   4   3   2   1

Additive inverses (x -> -x mod n):
 x | inv
----+----
  0 |   0
  1 |   7
  2 |   6
  3 |   5
  4 |   4
  5 |   3
  6 |   2
  7 |   1

Multiplicative inverses (x -> x^{-1

## GCD (Greatest Common Divisor)
$GCD(a,b)$is the largest number that divides both $a$ and $b$, if that number is 1 then $a$ and $b$ is  **coprime**

Euclidean GCD algorithm
$ gcd(a, b) = gcd(b, a mod b) stop until a mod b == 0$


In [10]:

def gcd(a, b):
    while b:
        print(f"GCD({a}, {b}) = GCD({b}, {a} mod {b}) = GCD({b}, {a % b})")
        a, b = b, a % b
    return a

print(gcd(55, 22))  # Output: 11
print(gcd(48, 18))  # Output: 6
print(gcd(11, 10))  # Output: 1 - co-prime

GCD(55, 22) = GCD(22, 55 mod 22) = GCD(22, 11)
GCD(22, 11) = GCD(11, 22 mod 11) = GCD(11, 0)
11
GCD(48, 18) = GCD(18, 48 mod 18) = GCD(18, 12)
GCD(18, 12) = GCD(12, 18 mod 12) = GCD(12, 6)
GCD(12, 6) = GCD(6, 12 mod 6) = GCD(6, 0)
6
GCD(11, 10) = GCD(10, 11 mod 10) = GCD(10, 1)
GCD(10, 1) = GCD(1, 10 mod 1) = GCD(1, 0)
1


In [11]:
def euclidean_steps(a, b):
    steps = []
    while b:
        q = a // b  # quotient
        r = a % b   # remainder
        steps.append(f"{a} = {b} × {q} + {r}, GCD({a}, {b}) = GCD({b}, {r})")
        a, b = b, r
    return steps

# Demonstrate with one of our previous examples
print("Euclidean Algorithm Steps for GCD(1970, 1066):")
for step in euclidean_steps(1970, 1066):
    print(step)

Euclidean Algorithm Steps for GCD(1970, 1066):
1970 = 1066 × 1 + 904, GCD(1970, 1066) = GCD(1066, 904)
1066 = 904 × 1 + 162, GCD(1066, 904) = GCD(904, 162)
904 = 162 × 5 + 94, GCD(904, 162) = GCD(162, 94)
162 = 94 × 1 + 68, GCD(162, 94) = GCD(94, 68)
94 = 68 × 1 + 26, GCD(94, 68) = GCD(68, 26)
68 = 26 × 2 + 16, GCD(68, 26) = GCD(26, 16)
26 = 16 × 1 + 10, GCD(26, 16) = GCD(16, 10)
16 = 10 × 1 + 6, GCD(16, 10) = GCD(10, 6)
10 = 6 × 1 + 4, GCD(10, 6) = GCD(6, 4)
6 = 4 × 1 + 2, GCD(6, 4) = GCD(4, 2)
4 = 2 × 2 + 0, GCD(4, 2) = GCD(2, 0)


# Finite Fields and Galois Fields

Finite fields are fields with a finite number of elements. They are fundamental in cryptography (AES, error-correcting codes, etc.) because they provide algebraic structures with predictable properties.

## Field axioms (brief)

A set F with two operations (addition and multiplication) is a field when the following hold:
1. Closure: for any a, b in F, a + b and a * b are in F.
2. Commutativity: a + b = b + a and a * b = b * a.
3. Associativity: (a + b) + c = a + (b + c) and (a * b) * c = a * (b * c).
4. Additive identity and inverses: there exists 0 in F with a + 0 = a; for every a there exists -a with a + (-a) = 0.
5. Multiplicative identity and inverses: there exists 1 != 0 in F with a * 1 = a; every nonzero a has an inverse a^{-1} with a * a^{-1} = 1.
6. Distributivity: a*(b + c) = a*b + a*c.

## Galois fields (GF(p^n))

- The order (number of elements) of a finite field is always a prime power: p^n, where p is prime and n >= 1 integer.
- When n = 1 we get the prime fields GF(p) (integers modulo p). When n > 1 we get extension fields GF(p^n).

### Examples (prime field GF(p))

- Example: arithmetic mod 29 (denote F_29).
  - Addition: 17 + 20 ≡ 37 ≡ 8 (mod 29).
  - Multiplication: 17 * 20 = 340 ≡ 21 (mod 29).

### Binary extension fields GF(2^n) (used in AES)

- Elements can be represented as binary polynomials (or n-bit vectors). Addition is bitwise XOR (polynomial addition mod 2). Multiplication is polynomial multiplication modulo an irreducible polynomial of degree n.
- AES uses GF(2^8) with the irreducible polynomial:

  x^8 + x^4 + x^3 + x + 1

#### GF(2^2) — small illustrative example

- Polynomial choice (one irreducible polynomial) : x^2 + x + 1 (root denoted α). The field elements can be written {0, 1, α, α+1}.
- Addition table (polynomial / bitwise XOR representation):

```
    + |  0   1  α  α+1
   ---+----------------
    0 |  0   1  α  α+1
    1 |  1   0  α+1 α
    α |  α  α+1 0   1
  α+1 | α+1  α  1   0
```

#### GF(2^3) — another small example

- Using an irreducible polynomial e.g. x^3 + x + 1, the field has 8 elements: {0, 1, α, α+1, α^2, α^2+1, α^2+α, α^2+α+1}.
- Elements are commonly represented by 3-bit binary sequences (000..111). Addition is XOR (component-wise mod 2). Multiplication requires reduction modulo the chosen irreducible polynomial.

Small schematic of chaining (addition vs multiplication):
```
Addition (bitwise XOR):      Multiplication (poly · poly mod irreducible):
  101
+ 011
= 110                      (101)·(011) -> multiply polynomials -> reduce mod p(x)
```

## Notes and practical points

- In GF(2^n) addition is extremely cheap (XOR). Multiplication is more complex and done with polynomial reduction; AES uses lookup tables and optimized routines.
- For theoretical work one chooses a convenient irreducible polynomial; for implementations use the standard polynomials (AES polynomial for GF(2^8)).
- Finite fields are crucial for producing uniform distributions and desirable diffusion properties in block ciphers and error-correcting codes.

In [12]:
def printPolynomialRepresentation(byte, degree=8):
    polynomial = []
    for i in range(degree):
        if byte & (1 << (degree - 1 - i)):
            if (degree - 1 - i) == 0:
                polynomial.append("1")
            elif (degree - 1 - i) == 1:
                polynomial.append("x")
            else:
                polynomial.append(f"x^{degree - 1 - i}")
    return " + ".join(polynomial) if polynomial else "0"

# Example usage
byte_value = 0b10011001
print("Polynomial representation of", bin(byte_value), "is:", printPolynomialRepresentation(byte_value))

Polynomial representation of 0b10011001 is: x^7 + x^4 + x^3 + 1


# Polynomial division

Polynomials over a field behave similarly to integers with division: for two polynomials f(x) and g(x) (with g(x) ≠ 0) there exist unique polynomials q(x) (quotient) and r(x) (remainder) such that

$$f(x) = q(x)\,g(x) + r(x),\qquad\deg(r) < \deg(g).$$

Here r(x) is the remainder and q(x) the quotient. We often write the remainder as

$$r(x) = f(x) \bmod g(x).$$

If g(x) cannot be factored (over the same field) into polynomials of lower degree, then g(x) is called irreducible (an analogue of a prime number for polynomials). Irreducible polynomials are used to construct extension fields GF(p^n).

### Example: reducible polynomial over GF(2)

Consider the polynomial $$f(x)=x^4+1\quad(\text{over }\mathrm{GF}(2)).$$ One factorization is

$$(x+1)(x^3+x^2+x+1) = x^4+1\quad\text{(expand and reduce coefficients mod 2)}.$$

Working the expansion over GF(2) (where addition is XOR):

- (x+1)(x^3+x^2+x+1) = x^4 + x^3 + x^2 + x + x^3 + x^2 + x + 1
- Pairwise cancellations (because 1+1 ≡ 0 mod 2) eliminate the repeated terms, leaving x^4 + 1.

Thus x^4 + 1 is reducible over GF(2) (it factors as shown).


AES irreducible polynomial
$m(x) = x^8 + x^4 + x^3 + x + 1$
 100011011 = 0x11B
 The irreducible polynomial is used to design the AES S-boxes, therefore it is dependent on GF(2^8) on that


In [13]:
def gf2n_add(a, b):
    """Add two elements a and b in GF(2^n) using polynomial representation."""
    print(f"Adding {a} and {b} in GF(2^n)")
    print(f"{printPolynomialRepresentation(a)}")
    print(f"+ {printPolynomialRepresentation(b)}")
    return a ^ b  # Addition in GF(2^n) is XOR

def gf2n_multiply(a, b, n, mod_poly=None, verbose=True):
    """Multiply two elements a and b in GF(2^n) with optional reduction by mod_poly.
    If mod_poly is None a sensible default is chosen for small n (n=2,3,8).
    When verbose=True the function prints step-by-step polynomial operations.
    Returns the integer representing the result in GF(2^n).
    """
    if mod_poly is None:
        if n == 8:
            mod_poly = 0x11B  # x^8 + x^4 + x^3 + x + 1 (AES)
        elif n == 3:
            mod_poly = 0b1011  # x^3 + x + 1
        elif n == 2:
            mod_poly = 0b111   # x^2 + x + 1
        else:
            mod_poly = None
    if verbose:
        print(f"Multiplying {a} (0b{a:0{n}b}) and {b} (0b{b:0{n}b}) in GF(2^{n})")
        print(f"a(x) = {printPolynomialRepresentation(a)}")
        print(f"b(x) = {printPolynomialRepresentation(b)}")
    result = 0
    # Accumulate shifted copies of a for each set bit in b
    for i in range(b.bit_length()):
        if (b >> i) & 1:
            term = a << i
            if verbose:
                print(f"\nBit {i} of b is 1 -> add a << {i}: {bin(term)} = {printPolynomialRepresentation(term)}")
                print(f"Before XOR result = {bin(result)} = {printPolynomialRepresentation(result)}")
            result ^= term
            if verbose:
                print(f"After XOR result  = {bin(result)} = {printPolynomialRepresentation(result)}")
    # Optional reduction modulo mod_poly
    if mod_poly is not None:
        mod_deg = mod_poly.bit_length() - 1
        if verbose:
            print(f"\nBegin reduction modulo m(x) = {bin(mod_poly)} = {printPolynomialRepresentation(mod_poly)} (degree {mod_deg})")
            print(f"Intermediate (pre-reduction) result = {bin(result)} = {printPolynomialRepresentation(result)}")
        step = 0
        while result.bit_length() - 1 >= mod_deg:
            step += 1
            deg_result = result.bit_length() - 1
            shift = deg_result - mod_deg
            shifted_mod = mod_poly << shift
            if verbose:
                print(f"\nReduction step {step}: deg(result)={deg_result}, shift={shift}")
                print(f" shifted m(x) = {bin(shifted_mod)} = {printPolynomialRepresentation(shifted_mod)}")
                print(f" Before XOR result = {bin(result)} = {printPolynomialRepresentation(result)}")
            result ^= shifted_mod
            if verbose:
                print(f" After  XOR result = {bin(result)} = {printPolynomialRepresentation(result)}")
        if verbose:
            print(f"\nFinal reduced result = {bin(result)} = {printPolynomialRepresentation(result)}")
    else:
        if verbose:
            print(f"\nNo modulus provided; raw polynomial product = {bin(result)} = {printPolynomialRepresentation(result)}")
    # Ensure the result fits into n bits (optional mask)
    mask = (1 << n) - 1
    return result & mask


def additiveInverseMatrixOverGF2n(n):
    size = 2 ** n
    matrix = np.zeros((size, size), dtype=int)
    for i in range(size):
        for j in range(size):
            matrix[i, j] = gf2n_add(i, j)
    return matrix

def multiplicativeInverseMatrixOverGF2n(n):
    size = 2 ** n
    matrix = np.zeros((size, size), dtype=int)
    for i in range(1, size):
        for j in range(1, size):
            if gf2n_multiply(i, j, n) == 1:
                matrix[i, 0] = i
                matrix[i, 1] = j
                break
    return matrix
  
# Demonstration polynomial multiplication
a = 0b00100110  # Example polynomial a(x)
b = 0b10011110  # Example polynomial b(x)
n = 8
print("\nPolynomial Multiplication in GF(2^8):")
result = gf2n_multiply(a, b, n, verbose=True)
print(f"Result: {bin(result)} = {printPolynomialRepresentation(result)}")

# Demonstration matrices of inverses
n = 2
add_mat_gf2n = additiveInverseMatrixOverGF2n(n)
mul_mat_gf2n = multiplicativeInverseMatrixOverGF2n(n)

print_matrix_table(add_mat_gf2n, 2**n, f'Addition table in GF(2^{n}):')

# TODO THIS IS WONG - FIX
print_matrix_table(mul_mat_gf2n, 2**n, f'Multiplication table in GF(2^{n}):')




Polynomial Multiplication in GF(2^8):
Multiplying 38 (0b00100110) and 158 (0b10011110) in GF(2^8)
a(x) = x^5 + x^2 + x
b(x) = x^7 + x^4 + x^3 + x^2 + x

Bit 1 of b is 1 -> add a << 1: 0b1001100 = x^6 + x^3 + x^2
Before XOR result = 0b0 = 0
After XOR result  = 0b1001100 = x^6 + x^3 + x^2

Bit 2 of b is 1 -> add a << 2: 0b10011000 = x^7 + x^4 + x^3
Before XOR result = 0b1001100 = x^6 + x^3 + x^2
After XOR result  = 0b11010100 = x^7 + x^6 + x^4 + x^2

Bit 3 of b is 1 -> add a << 3: 0b100110000 = x^5 + x^4
Before XOR result = 0b11010100 = x^7 + x^6 + x^4 + x^2
After XOR result  = 0b111100100 = x^7 + x^6 + x^5 + x^2

Bit 4 of b is 1 -> add a << 4: 0b1001100000 = x^6 + x^5
Before XOR result = 0b111100100 = x^7 + x^6 + x^5 + x^2
After XOR result  = 0b1110000100 = x^7 + x^2

Bit 7 of b is 1 -> add a << 7: 0b1001100000000 = 0
Before XOR result = 0b1110000100 = x^7 + x^2
After XOR result  = 0b1000010000100 = x^7 + x^2

Begin reduction modulo m(x) = 0b100011011 = x^4 + x^3 + x + 1 (degree 8)
Int

In [14]:

def polynomial_mod(fx, gx):
    """Debug version of polynomial_mod with step-by-step output"""
    print(f"Starting: fx = {bin(fx)}, gx = {bin(gx)}")
    
    deg_fx = fx.bit_length() - 1
    deg_gx = gx.bit_length() - 1
    
    print(f"Initial degrees: deg_fx = {deg_fx}, deg_gx = {deg_gx}")
    
    step = 1
    while deg_fx >= deg_gx:
        shift = deg_fx - deg_gx
        shifted_gx = gx << shift
        
        print(f"\nStep {step}:")
        print(f"  fx = {bin(fx)} (degree {deg_fx})")
        print(f"  gx shifted by {shift}: {bin(shifted_gx)}")
        
        fx ^= shifted_gx
        deg_fx = fx.bit_length() - 1
        
        print(f"  After XOR: fx = {bin(fx)} (degree {deg_fx})")
        step += 1
    
    print(f"\nFinal result: {bin(fx)}")
    return fx

def poly_gcd(fx, gx):
    while gx:
        print(f"GCD({bin(fx)}, {bin(gx)}) = GCD({bin(gx)}, {bin(polynomial_mod(fx, gx))})")
        fx, gx = gx, polynomial_mod(fx, gx)
    return fx

# Demonstration of polynomial GCD
print("\nPolynomial GCD Computation:")
fx = 0b1000010000100  # x^12 + x^7 + x^2
gx = 0b100011011      # x^8 + x^4 + x^3 + x + 1

result = polynomial_mod(fx, gx)
print(f"Polynomial Modulus Result: {printPolynomialRepresentation(result)}")
    


Polynomial GCD Computation:
Starting: fx = 0b1000010000100, gx = 0b100011011
Initial degrees: deg_fx = 12, deg_gx = 8

Step 1:
  fx = 0b1000010000100 (degree 12)
  gx shifted by 4: 0b1000110110000
  After XOR: fx = 0b100110100 (degree 8)

Step 2:
  fx = 0b100110100 (degree 8)
  gx shifted by 0: 0b100011011
  After XOR: fx = 0b101111 (degree 5)

Final result: 0b101111
Polynomial Modulus Result: x^5 + x^3 + x^2 + x + 1


In [15]:

# Finding the multiplicative inverse in GF(p)
# If GCD(m, b) = 1 then b has a multiplicative inverse module m

def extended_euclidean(m, b):
    """Extended Euclidean Algorithm to find the multiplicative inverse of b mod m"""
    a1, a2, a3 = 1, 0, m
    b1, b2, b3 = 0, 1, b
    q = 0
    print(f" Q  |  a1  |  a2  |  a3  |  b1  |  b2  |  b3 ")
    while b3 != 0 and b3 != 1:
        print(f"{q :>3} | {a1:>4} | {a2:>4} | {a3:>4} | {b1:>4} | {b2:>4} | {b3:>4}")
        q = a3 // b3
        t1, t2, t3 = a1 - q * b1, a2 - q * b2, a3 - q * b3
        a1, a2, a3 = b1, b2, b3
        b1, b2, b3 = t1, t2, t3

    if b3 == 0:
        raise ValueError(f"No multiplicative inverse for {b} mod {m}")
    
    if b3 == 1:
        return b2 % m  # Ensure the result is positive
    
    return None

def validate_multiplicative_inverse(hexb, hexbinverse, hexm):
    """Validate the multiplicative inverse by checking (b * b_inv) mod m == 1"""
    product = (hexb * hexbinverse) % hexm
    print(f"Validation: ({hexb} * {hexbinverse}) mod {hexm} = {product}")
    return product == 1

b = 0xc2 # "11000010"
binverse = extended_euclidean(0x11B, b) 
validate_multiplicative_inverse(b, binverse, 0x11B)
    
binverse = extended_euclidean(11872, 3)

 Q  |  a1  |  a2  |  a3  |  b1  |  b2  |  b3 
  0 |    1 |    0 |  283 |    0 |    1 |  194
  1 |    0 |    1 |  194 |    1 |   -1 |   89
  2 |    1 |   -1 |   89 |   -2 |    3 |   16
  5 |   -2 |    3 |   16 |   11 |  -16 |    9
  1 |   11 |  -16 |    9 |  -13 |   19 |    7
  1 |  -13 |   19 |    7 |   24 |  -35 |    2
Validation: (194 * 124) mod 283 = 1
 Q  |  a1  |  a2  |  a3  |  b1  |  b2  |  b3 
  0 |    1 |    0 | 11872 |    0 |    1 |    3


# Finding the mod inverse with Fermats theorem

In [16]:
def modinv_fermat(b, p):
    """Modular inverse of b modulo prime p using Fermat's little theorem.
    Requires p to be prime and b % p != 0. Returns x such that (b*x) % p == 1.
    """
    if p <= 1:
        raise ValueError("Modulus p must be a prime > 1")
    if b % p == 0:
        raise ValueError(f"{b} ≡ 0 (mod {p}) has no inverse")
    return pow(b, p - 2, p)

def modinv_fermat_verbose(b, p):
    """Verbose version of modular inverse using Fermat's little theorem."""
    if p <= 1:
        raise ValueError("Modulus p must be a prime > 1")
    if b % p == 0:
        raise ValueError(f"{b} ≡ 0 (mod {p}) has no inverse")
    exponent = p - 2
    print(f"Calculating modular inverse of {b} mod {p} using Fermat's theorem:")
    print(f"b^(p-2) ≡ b^{exponent} (mod {p})  = {b}^{exponent} mod {p}")
    result = pow(b, exponent, p)
    print(f"Result: {result}")
    return result

def modinv_fermat_binary_exponentiation(b, p):
    """Modular inverse of b modulo prime p using Fermat's little theorem with binary exponentiation.
    Shows detailed breakdown of how the exponent is decomposed.
    """
    if p <= 1:
        raise ValueError("Modulus p must be a prime > 1")
    if b % p == 0:
        raise ValueError(f"{b} ≡ 0 (mod {p}) has no inverse.")
    
    exponent = p - 2
    base = b % p
    result = 1
    
    # Show binary representation and decomposition
    binary_rep = bin(exponent)[2:]  # Remove '0b' prefix
    print(f"\n{'='*70}")
    print(f"Calculating modular inverse of {b} mod {p}")
    print(f"Using Fermat's Little Theorem: b^(p-2) mod p")
    print(f"{'='*70}")
    print(f"\nExponent: {exponent}")
    print(f"Binary:   {binary_rep} (base 2)")
    
    # Find which powers of 2 are in the decomposition
    powers = []
    temp_exp = exponent
    bit_pos = 0
    while temp_exp > 0:
        if temp_exp % 2 == 1:
            powers.append(bit_pos)
        temp_exp //= 2
        bit_pos += 1
    
    powers_str = " + ".join([f"2^{p}" for p in reversed(powers)])
    values_str = " + ".join([f"{2**p}" for p in reversed(powers)])
    print(f"Decomposition: {exponent} = {powers_str} = {values_str}")
    print(f"\nTherefore: {b}^{exponent} = {b}^({values_str})")
    print(f"{'='*70}\n")
    
    # Binary exponentiation with detailed steps
    current_power = 0
    step = 1
    
    while exponent > 0:
        bit = exponent % 2
        power_of_2 = 2 ** current_power
        
        print(f"Step {step}: Processing bit position {current_power} (2^{current_power} = {power_of_2})")
        print(f"  Current exponent: {exponent} (binary: {bin(exponent)[2:]})")
        print(f"  Current base: {b}^{power_of_2} ≡ {base} (mod {p})")
        print(f"  Current result: {result}")
        
        if bit == 1:  # If this bit is set
            print(f"  ✓ Bit is 1: Including {b}^{power_of_2} in result")
            print(f"    result = result × base = {result} × {base} ≡ {(result * base) % p} (mod {p})")
            result = (result * base) % p
        else:
            print(f"  ✗ Bit is 0: Skipping this power")
        
        # Square the base for next iteration
        next_base = (base * base) % p
        print(f"  Squaring base for next iteration: {base}² ≡ {next_base} (mod {p})")
        base = next_base
        
        exponent //= 2
        current_power += 1
        step += 1
        print()
    
    print(f"{'='*70}")
    print(f"Final result: {b}^{p-2} ≡ {result} (mod {p})")
    print(f"Verification: ({b} × {result}) mod {p} = {(b * result) % p}")
    print(f"{'='*70}\n")
    
    return result




# Example with smaller numbers for clarity
print("Example 1: Small numbers")
modinv_fermat_binary_exponentiation(3, 11)

print("\n" + "="*70 + "\n")

print("Example 2: Larger numbers")
modinv_fermat_binary_exponentiation(70, 271)

# Quick examples / demonstration
print("Inverse of 70 mod 271 ->", modinv_fermat_verbose(70, 271))  # expected 4 because 3*4 % 11 == 1
print("Inverse of 70 mod 271 ->", modinv_fermat(70, 271))  # expected 4 because 3*4 % 11 == 1
print("Inverse of 70 mod 271 ->", modinv_fermat_binary_exponentiation(70, 271))  # expected 4 because 3*4 % 11 == 1

print("Inverse of 15 mod 254 ->", modinv_fermat_binary_exponentiation(15, 254))  # expected 4 because 3*4 % 11 == 1

Example 1: Small numbers

Calculating modular inverse of 3 mod 11
Using Fermat's Little Theorem: b^(p-2) mod p

Exponent: 9
Binary:   1001 (base 2)
Decomposition: 9 = 2^3 + 2^0 = 8 + 1

Therefore: 3^9 = 3^(8 + 1)

Step 1: Processing bit position 0 (2^0 = 1)
  Current exponent: 9 (binary: 1001)
  Current base: 3^1 ≡ 3 (mod 11)
  Current result: 1
  ✓ Bit is 1: Including 3^1 in result
    result = result × base = 1 × 3 ≡ 3 (mod 11)
  Squaring base for next iteration: 3² ≡ 9 (mod 11)

Step 2: Processing bit position 1 (2^1 = 2)
  Current exponent: 4 (binary: 100)
  Current base: 3^2 ≡ 9 (mod 11)
  Current result: 3
  ✗ Bit is 0: Skipping this power
  Squaring base for next iteration: 9² ≡ 4 (mod 11)

Step 3: Processing bit position 2 (2^2 = 4)
  Current exponent: 2 (binary: 10)
  Current base: 3^4 ≡ 4 (mod 11)
  Current result: 3
  ✗ Bit is 0: Skipping this power
  Squaring base for next iteration: 4² ≡ 5 (mod 11)

Step 4: Processing bit position 3 (2^3 = 8)
  Current exponent: 1 (binary:

## Fermats modinverse in galois fields

In [19]:

def gf_mul(a, b):
    """Galois Field (2^8) multiplication used by AES (irreducible poly x^8 + x^4 + x^3 + x + 1).
    This is the usual bytewise implementation using 0x1B reduction on carry.
    """
    p = 0
    for _ in range(8):
        if b & 1:
            p ^= a
        carry = a & 0x80
        a = (a << 1) & 0xFF
        if carry:
            a ^= 0x1B
        b >>= 1
    return p & 0xFF

In [20]:
def gf_mult_inverse_verbose(a):
    """
    Find multiplicative inverse in GF(2^8) using exponentiation.
    Similar to Fermat's theorem but in Galois Field.
    Formula: a^(-1) = a^(2^8 - 2) = a^254 in GF(2^8)
    """
    if a == 0:
        print("Special case: inverse of 0x00 is defined as 0x00")
        return 0
    
    exponent = 254  # 2^8 - 2 = 256 - 2 = 254
    
    print(f"\n{'='*80}")
    print(f"MULTIPLICATIVE INVERSE IN GF(2^8) - Fermat-Style Method")
    print(f"{'='*80}")
    print(f"\nInput: 0x{a:02X} = {a:08b}b = {a} (decimal)")
    print(f"\nGoal: Find a^(-1) such that a • a^(-1) = 0x01 in GF(2^8)")
    print(f"\nFormula: a^(-1) = a^(2^8 - 2) = a^254 in GF(2^8)")
    print(f"  (Similar to Fermat's a^(p-2) but in Galois Field)")
    print(f"\nIrreducible polynomial: x^8 + x^4 + x^3 + x + 1 = 0x11B")
    print(f"All multiplications use GF(2^8) arithmetic with this polynomial")
    
    # Binary representation of exponent
    binary_rep = bin(exponent)[2:]
    print(f"\n{'─'*80}")
    print(f"EXPONENT DECOMPOSITION")
    print(f"{'─'*80}")
    print(f"Exponent: {exponent} (decimal)")
    print(f"Binary:   {binary_rep} (base 2)")
    
    # Find which powers of 2 are in the decomposition
    powers = []
    temp_exp = exponent
    bit_pos = 0
    while temp_exp > 0:
        if temp_exp % 2 == 1:
            powers.append(bit_pos)
        temp_exp //= 2
        bit_pos += 1
    
    powers_str = " + ".join([f"2^{p}" for p in reversed(powers)])
    values_str = " + ".join([f"{2**p}" for p in reversed(powers)])
    print(f"Decomposition: {exponent} = {powers_str}")
    print(f"             = {values_str}")
    print(f"\nTherefore: 0x{a:02X}^254 = 0x{a:02X}^({values_str})")
    
    # Binary exponentiation in GF(2^8)
    result = 1
    base = a
    power = exponent
    current_power = 0
    step = 1
    
    print(f"\n{'─'*80}")
    print(f"BINARY EXPONENTIATION IN GF(2^8)")
    print(f"{'─'*80}")
    print(f"Using repeated squaring with GF(2^8) multiplication\n")
    
    while power > 0:
        bit = power & 1
        power_of_2 = 2 ** current_power
        
        print(f"{'─'*80}")
        print(f"Step {step}: Bit position {current_power} (2^{current_power} = {power_of_2})")
        print(f"{'─'*80}")
        print(f"  Remaining exponent: {power} (binary: {bin(power)[2:]})")
        print(f"  Current base: 0x{a:02X}^{power_of_2} = 0x{base:02X} ({base:08b}b)")
        print(f"  Current result: 0x{result:02X} ({result:08b}b)")
        
        if bit == 1:
            print(f"  ✓ Bit is 1: Including 0x{a:02X}^{power_of_2} in result")
            old_result = result
            result = gf_mul(result, base)
            print(f"    result = result •GF base")
            print(f"           = 0x{old_result:02X} •GF 0x{base:02X}")
            print(f"           = 0x{result:02X} ({result:08b}b)")
        else:
            print(f"  ✗ Bit is 0: Skipping this power")
        
        # Square the base for next iteration
        if power > 1:  # Don't compute if this is the last iteration
            old_base = base
            base = gf_mul(base, base)
            print(f"\n  Squaring base for next iteration:")
            print(f"    base = base •GF base")
            print(f"         = 0x{old_base:02X} •GF 0x{old_base:02X}")
            print(f"         = 0x{base:02X} ({base:08b}b)")
        
        power >>= 1
        current_power += 1
        step += 1
        print()
    
    
    return result


# Example: Find inverse of 0x0F in GF(2^8)
print("\n" + "█"*80)
print("EXAMPLE: Finding 0x0F^(-1) = 0xC7 in GF(2^8)")
print("█"*80)

result = gf_mult_inverse_verbose(0x0F)

# Verify it matches expected value
expected = 0xC7
print(f"Expected value: 0x{expected:02X}")
print(f"Computed value: 0x{result:02X}")
print(f"Match: {'✓ YES' if result == expected else '✗ NO'}\n")




████████████████████████████████████████████████████████████████████████████████
EXAMPLE: Finding 0x0F^(-1) = 0xC7 in GF(2^8)
████████████████████████████████████████████████████████████████████████████████

MULTIPLICATIVE INVERSE IN GF(2^8) - Fermat-Style Method

Input: 0x0F = 00001111b = 15 (decimal)

Goal: Find a^(-1) such that a • a^(-1) = 0x01 in GF(2^8)

Formula: a^(-1) = a^(2^8 - 2) = a^254 in GF(2^8)
  (Similar to Fermat's a^(p-2) but in Galois Field)

Irreducible polynomial: x^8 + x^4 + x^3 + x + 1 = 0x11B
All multiplications use GF(2^8) arithmetic with this polynomial

────────────────────────────────────────────────────────────────────────────────
EXPONENT DECOMPOSITION
────────────────────────────────────────────────────────────────────────────────
Exponent: 254 (decimal)
Binary:   11111110 (base 2)
Decomposition: 254 = 2^7 + 2^6 + 2^5 + 2^4 + 2^3 + 2^2 + 2^1
             = 128 + 64 + 32 + 16 + 8 + 4 + 2

Therefore: 0x0F^254 = 0x0F^(128 + 64 + 32 + 16 + 8 + 4 + 2)

───────